### PR TITLE
Add create and update support to secret resource

### PR DESCRIPTION
**Pull request by rossf7**
Towards giantswarm/giantswarm#4845

Same deal. This is the basically the same as the configmap resource.

### CODE REVIEW

**Comment by tomahawk28** [comment]
Have you thought about using Pawel's change from Hakathon?

**Comment by kopiczko** [comment]
> Have you thought about using Pawel's change from Hakathon?

There is no generic `Secret` resource yet.

**Comment by rossf7** [comment]
@tomahawk28 See https://github.com/giantswarm/app-operator/pull/59#issue-259152732.

We will need extra logic for connecting to control plane clusters that is only needed in app-operator.

Everywhere else like in the `index` resources  you added and the upcoming `clusterconfigmap` resource in cluster-operator we can use the generic resource.

**Comment by rossf7** [comment]
> There is no generic Secret resource yet.

@kopiczko Yes we will likely need a generic secret resource at some point.

At the moment we don't need to generate any secrets in cluster-operator for the managed services but I think we will eventually.

**Comment by kopiczko** [comment]
> > There is no generic Secret resource yet.
> 
> @kopiczko Yes we will likely need a generic secret resource at some point.
> 
> At the moment we don't need to generate any secrets in cluster-operator for the managed services but I think we will eventually.

I'll try to generate one for `Secret` and `Namespace` this week. I think those two are the most common.

**Pull request merged**
