### PR TITLE
Use cc not ctlCtx

### PR DESCRIPTION
**Pull request by rossf7**
See https://github.com/giantswarm/fmt/pull/42. 

Democracy in action. You can't argue with PR #42.

### CODE REVIEW

**Comment by rossf7** [comment]
@xh3b4sd I looked but I don't see `sc` anywhere. What am I missing?

**Comment by xh3b4sd** [comment]
I have tomatoes on my eyes and thought this is the `aws-operator`.

**Comment by rossf7** [comment]
> I have tomatoes on my eyes 

❤️ 

OK cool going with this! We're cooking with water now. 😉

**Comment by xh3b4sd** [comment]
It goes more like, we all only cook with water after all. But yeah, definitely. :D

**Pull request merged**
