### PR TITLE
Only run podmonitor outside of bootstrap mode

### PR DESCRIPTION
**Pull request by MarcelMue**
## Checklist

- [x] Update changelog in CHANGELOG.md.

### CODE REVIEW

**Review by kopiczko — APPROVED** [review]

**Review by kubasobon — APPROVED** [review]
LGTM :rocket:

**Comment by MarcelMue** [comment]
@whites11 Can you check here? I have no idea how I could easily test if this fixes the current issues.

**Comment by whites11** [comment]
> @whites11 Can you check here? I have no idea how I could easily test if this fixes the current issues.

not really IMHO. There might still be race conditions where app operator in "production mode" gets deployed before the CR exists, right?

In other places we used to check if the CRD exists before creating the CR.
Example: https://github.com/giantswarm/azure-operator/blob/master/helm/azure-operator/templates/vpa.yaml#L1

Does it make sense to use that approach instead?

**Comment by MarcelMue** [comment]
> > In other places we used to check if the CRD exists before creating the CR. Example: https://github.com/giantswarm/azure-operator/blob/master/helm/azure-operator/templates/vpa.yaml#L1
> > Does it make sense to use that approach instead?
> 
> I think it may mean the PodMonitor is never created in some situations even though the CRD is eventually created.

Yes, I would rather have it fail in that case than have no monitoring of app-operator. Especially if we can't detect easily that monitoring is missing otherwise.

**Review by whites11 — APPROVED** [review]

**Pull request merged**
