### PR TITLE
Do not copy annotation from app

### PR DESCRIPTION
**Pull request by tomahawk28**
We are copying `annotation` in `app` CR into `chart` CR. 
We only need to copy `label`, not `annotation`.

### CODE REVIEW

**Comment by tomahawk28** [comment]
@rossf7 Can you help me on here to understand it? 
I really don't understand why `chart` is still remaining after delete. 
it pass this condition, https://github.com/giantswarm/app-operator/blob/1a12a1ccb24e6f0428c4ea72ec6cdb59158f0dce/service/controller/app/v1/resource/chart/delete.go#L75

**Comment by rossf7** [comment]
@tomahawk28 I'm not 100% but I think its because equals compares annotations.

https://github.com/giantswarm/app-operator/blob/1a12a1ccb24e6f0428c4ea72ec6cdb59158f0dce/service/controller/app/v1/resource/chart/resource.go#L88-L90

We should remove that too and just let k8s manage the annotations.

**Comment by tomahawk28** [comment]
Not only annotation but TypeMeta.Kind, APIVersion in `currentChart` are empty string but `desiredChart` had filled that information. Let me look at that pass as well.

**Comment by tomahawk28** [comment]
So it works! I will delete debug msgs and merged it :)

**Pull request merged**
