### PR TITLE
Print diff for appcatalogEntry CRs

### PR DESCRIPTION
**Pull request by tomahawk28**
## Checklist

- [ ] Update changelog in CHANGELOG.md.

### CODE REVIEW

**Comment by tomahawk28** [comment]
Tested in `gauss`

```
D 02/04 18:53:02 /apis/application.giantswarm.io/v1alpha1/appcatalogs/giantswarm-test appcatalogentry appCatalogEntry `giantswarm-test-prometheus-operator-app-0.6.0-eb5663b7866cb07783e4860e07099fbe054d67a0` has to be updated | app-operator/v3/service/controller/appcatalog/resource/appcatalogentry/create.go:89 | controller=app-operator-appcatalog | diff=(-current +desired):
  &v1alpha1.AppCatalogEntry{
  	TypeMeta:   {Kind: "AppCatalogEntry", APIVersion: "application.giantswarm.io/v1alpha1"},
  	ObjectMeta: {Name: "giantswarm-test-prometheus-operator-app-0.6.0-eb5663b7866cb07783"..., Namespace: "default", Labels: {"app.kubernetes.io/name": "prometheus-operator-app", "application.giantswarm.io/catalog": "giantswarm-test", "application.giantswarm.io/catalog-type": "test", "giantswarm.io/managed-by": "app-operator-unique", ...}, OwnerReferences: {{APIVersion: "application.giantswarm.io/v1alpha1", Kind: "AppCatalog", Name: "giantswarm-test", UID: "3b33019d-05e4-4bd6-bf47-87c185a0e2f0", ...}}, ...},
  	Spec: v1alpha1.AppCatalogEntrySpec{
  		AppName:    "prometheus-operator-app",
  		AppVersion: "0.43.2",
  		Catalog:    {Name: "giantswarm-test"},
  		Chart: v1alpha1.AppCatalogEntrySpecChart{
- 			APIVersion: "v3",
+ 			APIVersion: "v1",
  			Home:       "https://github.com/giantswarm/prometheus-operator-app",
  			Icon:       "https://s.giantswarm.io/app-icons/1/png/prometheus-operator-app-"...,
  		},
  		DateCreated: s"2021-02-01 16:52:55 +0000 UTC",
  		DateUpdated: s"2021-02-01 16:52:55 +0000 UTC",
  		... // 2 identical fields
  	},
  }
 | event=update | loop=10 | version=96442226
```

**Review by rossf7 — APPROVED** [review]
LGTM ❤️ 

But... #666 😅😱😈

**Comment by tomahawk28** [comment]
Don't worry, let's roll out PRs until it reaches 777.

**Comment by rossf7** [comment]
> Don't worry, let's roll out PRs until it reaches 777.

111 to go. Dependabot will help with that. 😂

**Pull request merged**
