### PR TITLE
Fixing helmclient

### PR DESCRIPTION
**Pull request by ljakimczuk**
## Checklist

- [ ] Update changelog in CHANGELOG.md.

### CODE REVIEW

**Comment by marians** [comment]
Will this not be overwritten by the Synchronize workflow? To change this, I think an override like this one is needed:

https://github.com/giantswarm/github/blob/main/repositories/override/app-build-suite/renovate.json

**Comment by ljakimczuk** [comment]
@marians it probably will but right now I am in the trial and error stage.

**Review by marians — COMMENTED** [review]
Go ahead then :)

**Comment by ljakimczuk** [comment]
@marians can I get an approval pls?

**Review by marians — APPROVED** [review]

**Pull request merged**
