### PR TITLE
Fix problems deleting chart CR, configmap and secrets

### PR DESCRIPTION
**Pull request by rossf7**
Towards https://github.com/giantswarm/giantswarm/issues/8187

### CODE REVIEW

**Comment by sslavic** [comment]
https://github.com/giantswarm/giantswarm/issues/8187 reproduced https://circleci.com/gh/giantswarm/app-operator/2440

**Comment by rossf7** [comment]
Tested on `gauss`.

**Comment by sslavic** [comment]
What do we do about existing ConfigMap and Secret orphaned resources laying around, labeled as managed by app-operator but not actually part of any existing App?

**Comment by rossf7** [comment]
@sslavic Good point on the orphan resources. I think we should add metrics for orphan configmaps and secrets to the app-operator collector.

I can work on the cleanup when I'm back on Friday.

**Pull request merged**
